version: "3.7"

services:

  database:
    image: tinkerpop/gremlin-server:latest
    ports:
    - ${DB_PORT:-8182}:8182
    volumes:
    - ${PWD}/api/src/test/resources/tinkergraph-overrides.properties:/opt/gremlin-server/conf/tinkergraph-empty.properties

  aws:
    image: localstack/localstack:latest
    ports:
    - 4566:4566
    volumes:
      - ${PWD}/api/src/test/resources/localstack-kms-storage:/tmp/local-kms
    environment:
    - SERVICES=ses,dynamo,kms,ssm
    - DEBUG=${AWS_DEBUG:-true}
    - DATA_DIR=/tmp/localstack/data
