---
server:
  applicationConnectors:
  - type: http
    port: ${PORT:-9000}
allowedOrigins: '*'

logging:
  level: ${ROOT_LOG_LEVEL:-INFO}
  loggers:
    io.zerobase: DEBUG
    # Enable errors from body processing
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG

database:
  endpoints:
    write: ${DB_HOST:-127.0.0.1}
  port: ${DB_PORT:-8182}

aws:
  ses:
    region: ${REGION:-us-east-1}
    endpoint: ${LOCALSTACK_ENDPOINT:-http://127.0.0.1:4566}
  s3:
    region: ${REGION:-us-east-1}
    endpoint: ${LOCALSTACK_ENDPOINT:-http://127.0.0.1:4566}
  sns:
    region: ${REGION:-us-east-1}
    endpoint: ${LOCALSTACK_ENDPOINT:-http://127.0.0.1:4566}

baseQrCodeLink: http://127.0.0.1:8080/s/

enableAllFeatures: true
features:
  - type: organizations
  - type: models
  - type: devices
  - type: admin
    config:
      ssm:
        region: us-east-1
        endpoint: ${LOCALSTACK_ENDPOINT:-http://127.0.0.1:4566}
      oauth:
        client: arn:aws:ssm:us-east-1:1234567890:parameter/dev-oauth
        callback: http://127.0.0.1:${PORT:-9000}/oauth/callback
      signing:
        endpoint: ${LOCALSTACK_ENDPOINT:-http://127.0.0.1:4566}
        key: arn:aws:kms:us-east-1:000000000000:key/bc6eec2c-a1bd-49a7-b90f-6234724789fa
      database:
        region: us-east-1
        endpoint: ${LOCALSTACK_ENDPOINT:-http://127.0.0.1:4566}
        tableName: admin-management

siteTypeCategories:
  BUSINESS: ["GROCERY", "RESTAURANT", "OTHER"]
  FINANCIAL: ["BANK", "OTHER"]
  HEALTH: ["DOCTOR_OFFICE", "HOSPITAL", "PHARMACY", "OTHER"]
  OTHER: ["OTHER"]
scannableTypes: ["QR_CODE"]
